### ISSUE TITLE
OpenAnnotate Viewer does not get triggered in IE

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#828] opened 2015-09-21 15:29 UTC
Configuring OpenAnnotate as the viewer does not seem to be getting tripped in IE. Everything works perfectly in Chrome, but IE is falling back to using Acrobat as the viewer. 

![vers](https://cloud.githubusercontent.com/assets/4850976/9996179/82ac7e6a-604b-11e5-97fe-24000d1285ea.gif)

Note, my Acrobat is messed up, but it normally would be showing Acrobat inline instead of the download dialog...

**Comment by m-brouillette** [comment] 2015-09-21 15:57
Should this be the intended behavior for versions of IE that OA doesn't support (IE <9)?

**Comment by gsteimer** [comment] 2015-09-21 16:32
@m-brouillette I'm seeing this on IE10 and IE11.

**Comment by gsteimer** [comment] 2015-09-23 16:53
We're thinking that this is just an incorrect browser check for OA compatibility.

**Comment by benallenallen** [comment] 2015-09-23 22:01
Seems the .sort call is doing something different in IE than it is in Chrome. It is sorting the stream viewer above the OA viewer even though the priority says it shouldn't be before it:

IE:
![2015-09-23 16_57_08-f12](https://cloud.githubusercontent.com/assets/4850976/10060126/92ed1e90-6214-11e5-86e0-6d1102c1a229.png)

Chrome:
![2015-09-23 16_58_51-developer tools - http___edge1 tsgrp com_hpi_stage_wizard_090000088002ed0e 7c090](https://cloud.githubusercontent.com/assets/4850976/10060144/a164f088-6214-11e5-8445-af973fe04200.png)

**Comment by renesaladrigas** [comment] 2015-09-28 21:37
OPEN ANNOTATE VIEWER: OpenAnnotate now is triggered in IE browser when it is configured in the viewer. Were using native sort algorithm, which was replaced with underscore sortBy algorithm using viewer priority.

CR - MBROUILLETTE

fixed with commit #13172

**Closed by renesaladrigas** 2015-09-28 21:37 UTC
Labels: issue, New Hire
