### ISSUE TITLE
Cancel AW Workflow - Activiti Metadata Blank in UI

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2240] opened 2020-08-21 16:29 UTC
See the screenshots below.  For some reason, the Cancel Wizard Review workflow metadata is blank.

Cancel AW Workflow (Review or Approval Route):
![image](https://user-images.githubusercontent.com/1377228/90913013-3a905a00-e3a1-11ea-9e1f-fa6b284c9a3a.png)

Cancel Non-AW Workflow To User (Looks good)
![image](https://user-images.githubusercontent.com/1377228/90912954-19c80480-e3a1-11ea-90cd-ea702e154983.png)

Cancel Non-AW Workflow To Group (Looks good)
![image](https://user-images.githubusercontent.com/1377228/90913103-5eec3680-e3a1-11ea-929e-42065b7862e5.png)

Acquire Non-AW Group Task (Looks good)
![image](https://user-images.githubusercontent.com/1377228/90913153-76c3ba80-e3a1-11ea-86cb-93b2ed72daa6.png)

Complete Non-AW Task (Looks good)
![image](https://user-images.githubusercontent.com/1377228/90912919-0b79e880-e3a1-11ea-948a-f33dbfded59e.png)

**Comment by mwojno-tsg** [comment] 2020-08-25 14:54
This issue was caused by OCMS rev: 25764 and GH issue: https://github.com/tsgrp/HPI/issues/2117

**Comment by mwojno-tsg** [comment] 2020-08-25 18:27
Closed with OC commit: **25798** and OCMS commit: **25798**. 
- The fix for this was primarily the `getTasks` function within the `IWorkflow` was filtering out tasks based on a white list. We wanted the `workflowutil` when it called `gettasks` endpoint to return all tasks to show the task property information. 

- That is why this only failed for the review and approval workflow. Therefore, we added a flag on the `gettasks` endpoint to decide whether to filter or not based on that defined whitelist in OC. 

CR: aking, nwoodbine

**Closed by mwojno-tsg** 2020-08-25 18:27 UTC
Labels: Active Wizard, Activiti Workflow, issue
