### ISSUE TITLE
Allow Active Wizard to Drive Mail Merge IF fields

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1743] opened 2018-07-27 14:18 UTC
Currently the Active Wizard can populate it's form from a Word Document with Mail Merge fields using a simple text replacement strategy.  It would be nice, however, to also support mail merge `IF` fields to include or exclude sections of the Word template based on Active Wizard answers.

For an example of how this works with HotDocs, see the demo screencam here:

http://www.tsgrp.com/solutions/contract-management-solution/

This could be a good add-on to fixing #1742

**Comment by grahamsinger** [comment] 2018-12-14 18:58
After more research, since we are using `docx4java` as our MailMerge "tool", `IF` statements don't seem supported.  We can look to use Aspose instead if we end up wanting to do this.

**Comment by grahamsinger** [comment] 2018-12-14 20:42
Confirmed works on Aspose.

**Comment by gsteimer** [comment] 2019-11-05 22:15
@kpelozatsgrp and @Swence32 worked to get this converted over to Aspose in the 3.3. release.  On edge however, it seems like conditional fields always display the "false" logic.  For example in our MSA template:

AW Form:
![image](https://user-images.githubusercontent.com/1377228/68250697-1072d480-ffe7-11e9-8dea-9dc957ab4b45.png)

Generated MSA Doc:
![image](https://user-images.githubusercontent.com/1377228/68250833-69db0380-ffe7-11e9-84de-12d488fe33a7.png)

![image](https://user-images.githubusercontent.com/1377228/68250807-5b8ce780-ffe7-11e9-8dd0-0d6768ffd8c5.png)

**Comment by gsteimer** [comment] 2019-12-03 20:53
Changing this to 3.3 since we've updated it to the point where it _shuold_ work with mail merge

**Comment by mwojno-tsg** [comment] 2019-12-12 16:01
The issue was resolved by making changes to the Master Services Agreement.docx to have the if fields conditional check against the display value, rather than the answer value. A quick fix did not seem apparent without breaking existing functionality to get it to compare against the value. Therefore, this issue is closed and an enhancement can be opened if we need to fix it to be compared against the value. OCMS Commit: 24392

**Closed by mwojno-tsg** 2019-12-12 16:01 UTC
Labels: Active Wizard, Contract Management Solution, issue
