### ISSUE TITLE
Deleted Documents are Not Removed From Tableview Until Refresh

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#1989] opened 2019-11-07 20:53 UTC
When deleting a document as a document action, the table view is not refreshed after the action. The document remains in the table view and allows you to click on it, triggering an error. You can delete multiple documents back to back and the table view does not refresh. If you refresh the page the documents are finally removed. See below images: 

![Delete Document (1)](https://user-images.githubusercontent.com/54869173/68426697-47272700-016e-11ea-8bd6-499cdbcef5a4.png)
![Delete Document (2)](https://user-images.githubusercontent.com/54869173/68426702-49898100-016e-11ea-9023-7177313a65a1.png)
![Delete Document (3)](https://user-images.githubusercontent.com/54869173/68426705-4b534480-016e-11ea-8d83-095fb5234757.png)
![Delete Document (4)](https://user-images.githubusercontent.com/54869173/68426707-4d1d0800-016e-11ea-9ea0-cd394e1a96fb.png)

**Comment by gsteimer** [comment] 2019-11-07 20:56
marking this as a duplicate of #1672

**Closed by gsteimer** 2019-11-07 20:56 UTC
Labels: tableview
