### ISSUE TITLE
After restarting OpenContent, AW form creation takes a long time

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2177] opened 2020-07-24 19:51 UTC
After restarting OC - whether through Alfresco or as a standalone WAR, the first time through creating an AW form seems to hang when OC is creating the form object and PDF.  To the user, it just sits here and spins:

![image](https://user-images.githubusercontent.com/1377228/88429692-aee4d700-cdbc-11ea-9768-d30ec7df4e8d.png)

On edge1 and release1 (Documentum), it's noticeable, but the form eventually loads and everything is fine.  On edge2 and release2 however, it takes so long that the request times out and the user sees this:

![image](https://user-images.githubusercontent.com/1377228/88429738-c58b2e00-cdbc-11ea-9a2e-74666b92d3a1.png)

There's no error in OC however since everything eventually works - it just takes a long time.  After a while (sometimes up to 5 minutes or so), the form is created and it's fine.

In either case, the second time through the processing is normal.  We should investigate what's going on here and fix it.  This seems to be something that has cropped up in the past few months, but it's hard to pinpoint exactly when.

**Comment by mwojno-tsg** [comment] 2020-07-29 21:03
If you edit a form the same behavior is experienced. It will time out but after a few minutes will resolve

**Comment by mwojno-tsg** [comment] 2020-08-03 16:04
I found this Aspose Forum: https://forum.aspose.com/t/slow-html-pdf-conversion/163394/6 that talks about the slow html -> pdf conversion. After three years, they said the issue is still unresolved

**Comment by mwojno-tsg** [comment] 2020-08-14 14:53
Hopefully resolved with OC commit: 25956

What we are doing in this commit is wiring a bean up called the AsposeBootstrapper. This will precache the license and the various inner api calls Aspose needs by creating a temp html file then deleting it. 

CR: ballen, dgrumieaux

**Closed by mwojno-tsg** 2020-08-14 14:53 UTC
Labels: Active Wizard, issue
