### ISSUE TITLE
Default Behavior with Missing Configurations

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1328] opened 2017-03-09 18:26 UTC
Upon logging in to HPI, HPI's first step is to attempt to load the dashboard and set your initial Trac context to one of the ones that your user has permission to. To do this, it needs to load configurations for your dashboard, Trac Configurations, and the Application config. 

If it is unable to load the expected configurations - even if it is WAD due to the user not having permission to any Tracs, for example - the user is redirected _immediately_ to the HPI Admin page, with instructions to create a new configuration.

This was previously intentional, as the only expected condition for not having configurations available was that none existed, and HPI was still being setup. However, the current behavior of users with no permissions being redirected to the Admin is not really desirable.

Moving forward, the default behavior should differentiate between an HPI with no configurations at all (How often does this happen nowadays?), and the user having no configuration access. If it is an instance of the latter (if configurations exist, but not Trac Configurations, in essence), we should display an error for the user. If it is an instance of the former, we can either keep the current behavior, or create a set of "default" configurations.

**Comment by gsteimer** [comment] 2017-10-30 19:05
Closed as duplicate of #1515

**Closed by gsteimer** 2017-10-30 19:05 UTC
Labels: duplicate, enhancement, HPI Admin
