### ISSUE TITLE
Bulk Import - Properties form not appearing not working on edge

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#782] opened 2015-08-17 19:12 UTC
See the screencam below - importing documents on edge2 is impossible because the properties form does not appear after choosing a type.  This happens if I try to import one document or multiple documents.

![bulk-import-form-support](https://cloud.githubusercontent.com/assets/1377228/9313684/e5b2da7c-44e9-11e5-9f9e-3ed7c30b2fc7.gif)

**Comment by grahamsinger** [comment] 2015-08-18 14:31
Not sure why, but this looks like it might be fixed?

From edge2:

![edge2upload](https://cloud.githubusercontent.com/assets/8784597/9332724/aedf7d5a-458b-11e5-91df-84ca91695142.gif)

**Comment by gsteimer** [comment] 2015-08-18 18:06
@grahamsinger - Hmm.... I'm still seeing the same thing even after clearing my cache and trying both IE and Chrome.  I did notice, however, that I'm only seeing this on the Insurance trac on edge2.  Although, it looks like that's what you are doing too...  I checked the bulk import action config for the Insurance trac and it looks ok to me.

Anyone else able to reproduce this?

**Comment by zkeller** [comment] 2015-08-18 18:10
I am seeing this on edge2 on my machine. It looks like an error with typeahead not being created when we try to set a value on it. I believe @ikaikajcorrea was looking at this at some point. I remember helping him with it. Did it make it into trunk?

**Comment by gsteimer** [comment] 2015-08-18 18:11
Ah - I bet that's why @grahamsinger isn't seeing it.  The documents inherit the folder properties, and one of the properties is a typeahead (status).

@grahamsinger - if you give your folder a status value and try again, then do you see the issue?

**Comment by gsteimer** [comment] 2015-08-18 18:12
That would also explain why we're just seeing this.  I just setup the status field on a typeahead a couple days ago.  For a long time it was just a freeform textbox.

**Comment by grahamsinger** [comment] 2015-08-18 18:13
Yeah I was just able to reproduce using an incognito browser.  My old configs must have been hanging around.

**Comment by grahamsinger** [comment] 2015-08-18 18:15
#746 might be the fix, and it looks like it might be done, pending a CR.

**Comment by grahamsinger** [comment] 2015-08-19 16:02
Fixed with rev12894.

Existing values now can pre-populate the autocomplete fields.  Also, if there happens to be a default value in addition to a pre-existing value, it will correctly use the pre-existing value instead of the default.

CR: ZK

**Closed by grahamsinger** 2015-08-19 16:02 UTC
Labels: High Priority, issue
