### ISSUE TITLE
View All Documents Fails to Reload When Other Actions Are Executed

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1346] opened 2017-03-28 18:32 UTC
When a user is using "View All Documents" as a right pane action, it appears there is an issue when coming back to the "View All Documents" action after it has been displayed once already. Can't tell if it is a race condition, or just something that happens with a specific set of steps, but all it takes to reproduce is:

1. Open up a document action on a document that was launched from "View All Documents"
1. Close the Document Action.
1. Click on "View all Documents" action
1. Repeat a 2nd time
1. Notice how the table columns are all squished and there is no data in the actual table
1. Also note that if I change the columns that are displayed, it actually re-draws and works correctly.

![issuegif2](https://cloud.githubusercontent.com/assets/4850976/24421165/e9d7a69a-13ba-11e7-9beb-e5dbc2e4688a.gif)

It is most noticeable in this 2nd scenario below for deleting a document which is a modal action, so not sure if that is significant.

![issuegif3](https://cloud.githubusercontent.com/assets/4850976/24421171/ec8440b0-13ba-11e7-99ec-08a787d1ed2d.gif)

**Comment by gsteimer** [comment] 2017-05-26 14:18
@benallenallen - is this a dupe of #1380 ?  If so, we can close this one as a dupe

**Comment by benallenallen** [comment] 2017-05-26 14:38
@gsteimer it is indeed a duplicate, but a slightly different set of steps that can reproduce it every time

**Comment by gsteimer** [comment] 2017-05-26 14:45
@benallenallen - ok, we can just close both issues when it's fixed.

**Comment by gpolonus** [comment] 2017-06-01 14:46
Fixed with commit #18049

**Closed by gpolonus** 2017-06-01 14:46 UTC
Labels: issue
