### ISSUE TITLE
Advanced Combined to PDF - Table of conents cuts off if more than 40 documents are being combined.

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#522] opened 2015-01-06 20:09 UTC
See screen shot below. there are 121 documents being combined and there is only one page for the table of conents and it cuts out at after 41 entries. There is no trace of any of the other table of contents entries. Places to start looking: AdvancedCombineToPDFActionExecuter.java in the method prependTitlePage which can be found at line 247.

![advancedcombinetopdf_tableofcontents](https://cloud.githubusercontent.com/assets/2895070/5635313/a162f37a-95ad-11e4-83db-588b7a32091b.png)

**Comment by gsteimer** [comment] 2015-01-07 18:04
@dhartman25 - will this be an issue for your client?

**Comment by tconnellytsg** [comment] 2015-01-08 14:55
Based on my past projects with pdf manipulation im 99% sure what the problem is here.  In the prependTitlePage method, as we loop through the tableofcontents map we make the link with link = new PdfAnnotation(copy, 36, ct.getYLine(), 559, y, action); where y is the height to draw at, and then y gets incremented.  The problem with this is that all text is in a pdf document is a series of commands to draw the specified characters at certain locations, and there is no real concept of page wrapping text, so as y grows, the y location that we are drawing the text at is OFF the page.  (This won't throw an error for better or for worse)

A couple possible solutions:
1.  Add code to detect when y has grown to big and is now off the page, and add a new page to the pdf document and reset y(kinda hacky).
2.  Use a freemarker template to generate an html sheet with the passed in data, and then use itexts' XmlWorkerHelper class to parse the html to a pdf.

**Comment by dhartman25** [comment] 2015-01-08 17:03
@gsteimer - yes, I'm sure Gallagher will run into this, so we'll want to fix this before we get into their QA/Prod

**Comment by alieblich** [comment] 2016-10-06 15:18
fixed with OC rev#14732

**Closed by alieblich** 2016-10-06 15:18 UTC
Labels: issue
