### ISSUE TITLE
Table View - Search Notifier Icons

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#873] opened 2015-10-23 21:43 UTC
Now that table view has the ability to show an icon based on the value stored in a meta-data field, this could be configured to show an icon for any field that interests a client. Instead of having only one attribute and a truthy value to check against in the back end, the config could allow the user to specify which attribute, what value, and what icon to show. That way, if there is a Yes/No flag, or another attribute that interests a client such as lockedBy, the table view search results could show a glyphicon to represent it.

**Comment by gsteimer** [comment] 2016-01-29 16:20
Bumping this to the 2.5 milestone since we've had multiple clients request that a key icon be placed next to search results when a document is checked out.

The admin config currently looks like this:

![image](https://cloud.githubusercontent.com/assets/1377228/12680750/1a8dcdd4-c671-11e5-929e-b2968d8e3933.png)

We'll have to update the admin to make this more generic.  Specifically:

- More generic name for the type control (Root type for icon display - something like that?)
- More config after selecting the type
  - Select the attribute
  - Select what you're checking for.  
    - Need to have have boolean available for the document notes indicator
    - String - pattern match.  Must allow for:
      - Equal to the logged in user's ID (Alfresco) or name (Dctm).  This should work similarly to saved search dashlets.  We'll want to show a key icon if the lock attr is set to the logged in user.
      - Blank or not.  We'll want to show a padlock icon when the value is not the logged in user, but not blank
      - Allow for some sort of precedence (see above).  I'm guessing first wins is easiest.
  - Select which icon should appear

**Comment by dgrumieaux** [comment] 2016-01-29 16:51
+1 from my current client

**Comment by dgrumieaux** [comment] 2016-01-29 19:36
Also should have a hover field that the user can hover over the icon and see some text.

**Comment by ZachGerth** [comment] 2016-02-15 17:04
Implemented with Revision #14323. Right now, the JSON is customizable in a config-project by configuring the tableview module. In the future, this should be configured from admin.

The specialIcon is configured by having a "specialIcon" object sent to the module, which itself consists of attributes which wish to be configured. Each attribute should have an object which contains the attribute to compare a regex against, a default value(for when it fails to match against the regex, but the attribute exists), and an optional tooltip option for when you hover over an icon. 

The regex object which will be compared against contains a value, for when it matches against the regex, and a pattern; this pattern can be a hardcoded special value, or $user.loginName, or $user.displayName, for the user's login/display username, respectively.
An example of this structure follows:

`    
"tableview": {//required
        specialIcon: {//required
            "documentNumber": {//any attribute
                attrDependency: "lockOwner",//any attribute to compare against
                regex: {//the regex object
                    pattern: "$user.displayName",//a pattern to match against OR the user's login/display
                    value: "glyphicons-keys"//the icon to inject
                },
                defaultValue :"glyphicons-lock",//the icon to inject if the attr exists, but isn't matched
                tooltip: true //flag to set an optional tooltip on the icon
            }
        }

    }
`

Note that in the future, we will probably want foldernotes to be incorporated into this change, as well.

**Comment by grahamsinger** [comment] 2016-06-20 21:27
Implemented with rev 15409

**Comment by mikeblum** [comment] 2016-06-24 15:29
In my testing for TableView, this doesn't support the scenario of having icons attached to `boolean` attributes in place of the text `true / false`. After talking to @gsteimer  we need to support the following scenarios:

* Lock Owner - show the lock or key icon next to the configured linked attribute (current functionality)
* Boolean attributes - if configured to be next to itself:

![selection_115](https://cloud.githubusercontent.com/assets/3905463/16342193/77e21b40-39f6-11e6-93cc-a5f4f50dd589.png)


we should show the icon if the regex expression is true or blank if false.

**Comment by gsteimer** [comment] 2016-06-24 15:32
@mikeblum the Lock owner scenario should be covered in @grahamsinger's updates.  The things we need to add / test are:

- [ ] Make sure that when configuring that icons show up next to a certain attribute, they actually do (vs. always showing up next to the linked attr)
- [ ] When adding an icon next to a boolean attribute, if the attr is not the linked attribute, then hide the true/false text and _only_ display the icon

**Comment by mikeblum** [comment] 2016-06-24 15:39
right I just wanted to have the regression test in the list.

**Comment by gsteimer** [comment] 2016-07-26 16:55
Trying this out on edge2, search seems to fail when an icon is configured:

![image](https://cloud.githubusercontent.com/assets/1377228/17147275/bb143cb4-5327-11e6-8c4b-72d0f7fac080.png)

Looks like the code is bombing when one of the results _doesn't_ have a value for the target property

**Comment by grahamsinger** [comment] 2016-07-26 17:25
Above issue fixed with rev15689

**Comment by gsteimer** [comment] 2016-07-29 15:58
After taking a look at this, I think we need to add the following as well:

- [ ] Currently, there's no ability to compare information to the logged in user.  This would be really useful for the key/lock scenario.  For example:
  - If the `lockOwner` attribute equals `$user.loginName`, show a key icon
  - If the `lockOwner` is not blank and does not equal `$user.loginName`, show a lock icon
    - Note: we should be able to do this with the one regex field.  No need to include and/or functionality in the admin interface
  - If the `lockOwner` is blank, show nothing

**Comment by gsteimer** [comment] 2016-12-06 20:48
while looking into this, we should also take a look at the admin.  When adding a new type to the Type Configurations, the indicator icons section is blank:

![image](https://cloud.githubusercontent.com/assets/1377228/20942872/e6ddfc8c-bbc2-11e6-83f3-b1122b38b066.png)

Once you save the type and go back, it appears correctly:

![image](https://cloud.githubusercontent.com/assets/1377228/20942889/fc553fb2-bbc2-11e6-8343-586de1f64658.png)

**Comment by rosenoam** [comment] 2016-12-09 21:36
Revision # 16796
Fixed issue when adding a new type to the Type Configurations, the indicator icons section is blank and but once you refresh it appears. It no longer does that, it appears as soon as you configure it.

**Comment by gsteimer** [comment] 2017-05-24 15:40
A couple more things we should add to the enhancement list:

- [ ] Currently, when displaying an icon, you can configure a hovertext message.  However, the text is static.  It would be nice if you could inject OCO properties using the token syntax.  The best example of this would be the lock icon.  Hovering over the lock should display a message like: "Document locked by: ${lockOwner}".  I think we could pull this off by assuming that if the token isn't `date` or doesn't start with `user.`, then check to see if the OCO has the value given (based on property OC name).
- [ ] The key/lock setup is very common.  Let's give the admin a link to quickly add the key and lock icons to table view config.

**Closed** 2017-05-26 14:43 UTC
Labels: enhancement, issue, New Hire
