### ISSUE TITLE
Public Saved Search - message disappears

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1438] opened 2017-07-17 19:27 UTC
When running a public saved search, the interface displays when an who last last modified the search.  It looks like this message is displaying, but is quickly removed when the search is finished:

![public-saved-search-message](https://user-images.githubusercontent.com/1377228/28285903-ff350652-6afb-11e7-94cc-c7ac33a153cc.gif)

**Comment by gsteimer** [comment] 2017-09-21 14:33
Also - it looks like the select box for normal saved searches is resetting as well:

![saved-search-disappear](https://user-images.githubusercontent.com/1377228/30701459-ee442e80-9eaf-11e7-9264-0e2eafca01ff.gif)

**Comment by kgarelli** [comment] 2017-10-17 14:39
The message appears but then the page renders a second time when the search is run. I attempted to pass the modifier and modified date values that are needed to render the message from savedSearch.js to searchsidebar.js then back to savedSearch.js so that they will be included in the serialize fcn in savedSearch and rendered into the message after the second render. This was done by using the url and parsing the url param in searchrouter.js. We thought this would work but might be a bit sloppy so then attempted to change instead how we access the searchURL in executeSearch method in searchsidebar updating the history.navigate call to include the parameter {"trigger":"false"} and removing the history.loadUrl call but this was only working occasionally.

**Comment by henryerzinger** [comment] 2018-01-02 14:41
SEARCH REFRESH -Fixed issue with Public Saved Search information disappearing on the search sidebar.  Issue was caused by the search running twice and reloading the page.  Search now loads just once.

CR - Joe Hof

Revision: 19462

**Closed by henryerzinger** 2018-01-02 14:41 UTC
Labels: issue, New Hire
