### ISSUE TITLE
Chain Versionable - Versioning workflow document attached to form does not move workflow doc relationship to new version

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1513] opened 2017-10-27 13:08 UTC
See the screenshots below.  I tested this with a 0.x Draft and a 1.x Draft and they're both doing the same thing:

Attached documents:
![image](https://user-images.githubusercontent.com/1377228/32105216-518e5a70-baed-11e7-9a0f-46d866707d19.png)

Edit `TSG-112` v0.1 and version to 0.2

Attached documents:
![image](https://user-images.githubusercontent.com/1377228/32105304-9affcefa-baed-11e7-9164-f8a0e46522ad.png)

Version history for `TSG-112`:
![image](https://user-images.githubusercontent.com/1377228/32105321-ac4ec2ba-baed-11e7-9818-586f4f332e8d.png)

Form is still attached to 0.1:
![image](https://user-images.githubusercontent.com/1377228/32105425-0f1410bc-baee-11e7-8ec0-b488df46bdba.png)

**Comment by Beamed** [comment] 2017-10-27 13:16
@gsteimer Does this occur if you create the form on the document? If so, this is a regression.

**Comment by gsteimer** [comment] 2017-10-27 13:21
I did it this way:

1. create the form
1. attach document(s)
1. version document
1. relationship doesn't move

I can try it by creating the form from the document and see if that "fixes" it, but that's only one valid use case.  There's definitely a few clients that set up their forms first and then attach documents.

**Comment by Beamed** [comment] 2017-10-27 13:23
Right - I'm thinking that it might be related to a more recent update, since the path for maintaining that association is the same across the two functionalities, so if we know it happens with forms or not helps indicate where to look.

**Comment by gsteimer** [comment] 2017-10-27 13:26
@ZachGerth - it definitely happens in the scenario where you create the form from the document as well.  Either way, we need to test both scenarios

**Comment by ZachGerth** [comment] 2017-10-30 16:21
Fixed with CVN Revision # 9346.

**Closed by ZachGerth** 2017-10-30 16:21 UTC
Labels: Alfresco, Contract Management Solution, Controlled Doc Solution, High Priority, issue
