### ISSUE TITLE
Better routing needed when no configs present

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1515] opened 2017-10-27 15:15 UTC
Currently, when HPI detects that there are no configs in the repository, the code assumes that it's the first time HPI has loaded and the user must be looking for the HPI Admin, so it routes the user to `/admin`.

There's a glaring problem with this now that we have Trac Security - if a user logs in and has _no_ permissions on any tracs, then the code assumes there's no configs and incorrectly routes the user to `/admin`.  Instead, we should do this:

1. If upon login, no configs are detected, take the user to a view that says that the system is unavailable.
1. If the user is an admin, provide a button to take the user to `/admin`
1. If the user is not an admin, simply have a button to log out

For each of the above cases, we can tweak the wording to better reflect what's going on.

@nquillin91 - one question - how will we know if the user is an admin?  If no configs are present, we're not going to have the app config to see what group is the admin group.  Is it just going to be some sort of "backup admin group" configured in the `config-project.js` or somewhere else?

**Comment by gsteimer** [comment] 2017-10-27 18:44
@CRdouglas - along with testing the trac security scenario (HPI configured, but user doesn't have access to any tracs), we also need to test the scenario where it's the first time HPI has been accessed an no configs exist.  The user (if they're an admin), should be able to get to `/admin` and the Config Archiver section in particular (so that he/she can upload configs that were archived from another environment).

**Comment by ZachGerth** [comment] 2017-10-30 16:23
Is this a duplicate of 1328 ? If so, we should close that one, since I think this one better lays out the scenarios to resolve.

**Comment by gsteimer** [comment] 2017-10-30 19:05
@ZachGerth - yep, thanks for the heads up

**Comment by CRdouglas** [comment] 2017-11-10 17:33
HPI Revision #19129

**Closed** 2017-11-10 17:34 UTC
Labels: enhancement, HPI Admin, question

**Comment by CRdouglas** [comment] 2017-11-13 14:50
HPI Revision #19136
