### ISSUE TITLE
Combine Alfresco OOTB Auditing with AW Obsolete Audit

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#605] opened 2015-03-10 21:35 UTC
Alfresco provides out of the box auditing when the following properties are set in the `alfresco-global.properties` file:

``` properties
#Audit Configuration
audit.enabled=true
audit.alfresco-access.enabled=true
audit.alfresco-access.sub-actions.enabled=true
audit.alfresco-access.sub-events.enabled=true

### Audit Filter ###
audit.filter.alfresco-access.default.enabled=true
audit.filter.alfresco-access.transaction.user=~System;.*
audit.filter.alfresco-access.transaction.type=aw:controlledDocument;tsg:controlled;tsg:approvable;tsg:departmentable;tsg:effectiveable;tsg:obsoleteable;tsg:periodicReviewable
audit.filter.alfresco-access.default.path=/app:company_home/.*
```

However, our code in `AlfrescoEmbAuditImpl` currently only pulls audit entries from the `ocAudit` application.  

When originally looking into this, I turned on the alfresco auditing as above, and then set the following, thinking that we'd need to search across all audit applications:

``` Java
AuditQueryParameters parameters = new AuditQueryParameters();
parameters.setApplicationName(null);
```

While this works, we ran into many hurdles, namely that Alfresco doesn't audit the object ID by default.  @parzgnat got this to work by adding the following line to `alfresco-audit-access.xml` :

(within the `<AuditPath key="transaction">`)

``` xml
<RecordValue key="node" dataExtractor="simpleValue" dataSource="/alfresco-access/transaction/node" dataTrigger="/alfresco-access/transaction/node" />  
```

Using the above, I can query for audit events by ID using the following (note the conversion from String to NodeRef - thanks, @dgrumieaux!):

``` Java
AuditQueryParameters parameters = new AuditQueryParameters();
parameters.addSearchKey("/alfresco-access/transaction/node", new NodeRef(objectId));
```

Based on all of the above, here's the path that @parzgnat @benallenallen @dgrumieaux  and I came up with:
1. We should not be modifying the `alfresco-audit-access.xml` file.  Instead, we (hopefully) can expand the ocAudit application to include items from the OOTB audit (like property updates).
2. Assuming the above works, update the code in `AlfrescoEmbAuditImpl` to pull back property update audits properly along with Obsolete audits (see #600).
3. If we can't get ocAudit to include property updates, then we'll need to go the route of:
   - Modify the `alfresco-audit-access.xml` to include the objectId in audit entries (not ideal)
   - Update `AlfrescoEmbAuditImpl to search across all audit applications
   - Selectively pull out the correct audit events (there is a crazy amount of READ events and login/logout events that I'm assuming we'll want to ignore).  Perhaps we can filter those out from even being audited?  That would be ideal since otherwise they're just going to blow out the size of the audit table.
   - Somehow combine the results from the OOTB audit with the Obsolete audit event in the ocAudit application (with the collections sorted properly) and then return the combined list to HPI.

**Comment by gsteimer** [comment] 2015-03-11 01:29
More notes for when we start this... if we can somehow get 1 above to work properly, I'm wondering if we can also get the OOTB nodeId and our auditedObjectId to use the same key (one or the other).  If we can do that, as well as make them both either `String` or `NodeRef`, then it should be trivial to query for both ocAudits (Obsolete) and OOTB Alfresco audits at the same time...

**Comment by Swence32** [comment] 2015-06-24 16:51
> expand the ocAudit application to include items from the OOTB audit (like property updates).

Expanded the ocAudit application configuration to match that of the base alfresco-access application (minus login/logout events) Will catch property updates, moves, copies, and aspect addition/removal.

```
<?xml version="1.0" encoding="UTF-8"?>

<Audit xmlns="http://www.alfresco.org/repo/audit/model/3.2"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.alfresco.org/repo/audit/model/3.2 alfresco-audit-3.2.xsd">

	<!-- we need to make an "application" to hold our audits for core OC auditing - this is ALL we need though, there's
	no definition of the "application" that needs to be made -->
  <DataExtractors>
     <DataExtractor name="simpleValue" registeredName="auditModel.extractor.simpleValue"/>
  </DataExtractors>

  <DataGenerators>
     <DataGenerator name="currentUser" registeredName="auditModel.generator.user"/>
  </DataGenerators>

  <PathMappings>
    <PathMap source="/alfresco-access" target="/ocAudit" />
  </PathMappings>

  <Application name="ocAudit" key="ocAudit">
      <AuditPath key="transaction">
          <RecordValue key="action" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/action" dataTrigger="/ocAudit/transaction/action" />
          <RecordValue key="sub-actions" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/sub-actions" dataTrigger="/ocAudit/transaction/sub-actions" />
          <RecordValue key="user" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/user" dataTrigger="/ocAudit/transaction/user" />

          <RecordValue key="path" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/path" dataTrigger="/ocAudit/transaction/path" />
          <RecordValue key="type" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/type" dataTrigger="/ocAudit/transaction/type" />
          <RecordValue key="version" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/cm:versionLabel" dataTrigger="/ocAudit/transaction/cm:versionLabel" />

          <AuditPath key="copy">
              <AuditPath key="from">
                  <RecordValue key="path" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/copy/from/path" dataTrigger="/ocAudit/transaction/copy/from/path" />
              </AuditPath>
          </AuditPath>

          <AuditPath key="move">
              <AuditPath key="from">
                  <RecordValue key="path" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/move/from/path" dataTrigger="/ocAudit/transaction/move/from/path" />
              </AuditPath>
          </AuditPath>

          <AuditPath key="properties">
              <RecordValue key="fromName" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/properties/from/name" dataTrigger="/ocAudit/transaction/properties/from/name" />
              <RecordValue key="toName" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/properties/to/name" dataTrigger="/ocAudit/transaction/properties/to/name" />
              <RecordValue key="from" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/properties/from" dataTrigger="/ocAudit/transaction/properties/from" />
              <RecordValue key="to" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/properties/to" dataTrigger="/ocAudit/transaction/properties/to" />
              <RecordValue key="add" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/properties/add" dataTrigger="/ocAudit/transaction/properties/add" />
              <RecordValue key="delete" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/properties/delete" dataTrigger="/ocAudit/transaction/properties/delete" />
          </AuditPath>

          <AuditPath key="aspects">
              <RecordValue key="add" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/aspects/add" dataTrigger="/ocAudit/transaction/aspects/add" />
              <RecordValue key="delete" dataExtractor="simpleValue" dataSource="/ocAudit/transaction/aspects/delete" dataTrigger="/ocAudit/transaction/aspects/delete" />
          </AuditPath>
      </AuditPath>

  </Application>

</Audit>
```

**Comment by Swence32** [comment] 2015-06-24 18:33
Example of ocAudit print out after adding an aspect and updating a property:

```
C:\Users\dswenson>curl -u admin:admin "http://localhost:8080/alfresco/service/api/audit/query/ocAudit?verbose=true"
{
   "count":2,
   "entries":
   [
      {
         "id":302,
         "application":"ocAudit",
         "user":"admin",
         "time":"2015-06-24T13:32:13.898-05:00",
         "values":
         {
                     "\/ocAudit\/transaction\/path":"\/app:company_home\/cm:CheckPath\/cm:CheckPath 2008\/cm:CheckPath CP 0031_01.tif"
                     ,"\/ocAudit\/transaction\/user":"admin"
                     ,"\/ocAudit\/transaction\/aspects\/add":"[{http:\/\/www.alfresco.org\/model\/content\/1.0}complianceable]"
                     ,"\/ocAudit\/transaction\/type":"whp:path-image"
                     ,"\/ocAudit\/transaction\/action":"addNodeAspect"
                     ,"\/ocAudit\/transaction\/sub-actions":"addNodeAspect"
                     ,"\/ocAudit\/transaction\/node":"workspace:\/\/SpacesStore\/95dd73bf-c1ab-4b11-8af5-cb8b743639dc"
         }

      },
      {
         "id":304,
         "application":"ocAudit",
         "user":"admin",
         "time":"2015-06-24T13:32:21.621-05:00",
         "values":
         {
                     "\/ocAudit\/transaction\/properties\/from":"{{http:\/\/www.alfresco.org\/model\/content\/1.0}modified=Wed Jun 24 13:32:13 CDT 2015, {ascp.product.model}path-image-type=G
ross Sample}"
                     ,"\/ocAudit\/transaction\/properties\/to":"{{http:\/\/www.alfresco.org\/model\/content\/1.0}modified=Wed Jun 24 13:32:21 CDT 2015, {ascp.product.model}path-image-type=Sl
ide Image}"
                     ,"\/ocAudit\/transaction\/path":"\/app:company_home\/cm:CheckPath\/cm:CheckPath 2008\/cm:CheckPath CP 0031_01.tif"
                     ,"\/ocAudit\/transaction\/properties\/add":"{{http:\/\/www.alfresco.org\/model\/content\/1.0}removeAfter=null}"
                     ,"\/ocAudit\/transaction\/user":"admin"
                     ,"\/ocAudit\/transaction\/type":"whp:path-image"
                     ,"\/ocAudit\/transaction\/action":"updateNodeProperties"
                     ,"\/ocAudit\/transaction\/node":"workspace:\/\/SpacesStore\/95dd73bf-c1ab-4b11-8af5-cb8b743639dc"
                     ,"\/ocAudit\/transaction\/sub-actions":"updateNodeProperties"
         }

      }
   ]
}
```

**Comment by Swence32** [comment] 2015-06-25 20:50
Per @mikeblum 's suggestion, I've confirmed that setting the audit search key to NULL will force the query to search for the given value, regardless of the key value. This will allow us to search on both the  OOTB node key and the original OCAuditEvent auditedObjectId key (for legacy data)

```
parameters.addSearchKey(null, new NodeRef(objectId));
```

**Comment by gsteimer** [comment] 2015-06-25 20:57
@Swence32 @mikeblum - are there any repercussions when it comes to speed though?  Some client's audit trails will get really huge.  Basically, I'm wondering if this is indexed somehow.  If that's the case, searching based on an indexed key is going to be faster than searching everything.

**Comment by Swence32** [comment] 2015-06-25 21:45
@gsteimer @mikeblum - Its possible that the performance will degrade as more and more audits are added to the application, but I don't have enough audits on my local Alfresco to get an idea of the degradation. This solution is really only for any "legacy" audits (which there will likely be none of, but at least we have proven that this implementation works).

The next step is to refactor the keys for Alfresco audits so that we can search on one universally indexed key. If I'm not mistaken, but Alfresco and DCTM utilize the OCAuditEvent POJO. Since we will want to change the key constants for Alfresco only, we will need to create two separate OCAuditEvent POJOs.

**Comment by gsteimer** [comment] 2015-06-26 12:05
@Swence32 - sounds good.  I didn't realize we were only using the `null` approach for legacy clients (if it's even needed). 

As to your second paragraph, I don't think we want to create two `OCAuditEvent` POJOs.  To me, that's just confusing.  Can't we just create event key constants directly in `AlfrescoEmbAuditImpl` and use those instead in Alfresco specific code?

**Comment by Swence32** [comment] 2015-07-24 16:47
@gsteimer - Looking at it again, that does seem like the easiest route. I'll create the new key constants in the ```AlfrescoEmbAuditImpl``` and verify creating and reading audits still functions properly.

**Comment by Swence32** [comment] 2015-08-18 19:57
A new branch has been created for the updates to the ocAudit.xml and AlfrescoEmbAuditImpl.java. Alfresco audits are now appearing in a readable format in the HPI audit modal.

**Comment by gsteimer** [comment] 2015-08-18 19:59
@Swence32 - is this ready to merge back to trunk and put on edge2?  I'm out this week, but feel free to review it with @benallenallen and @dgrumieaux.

Once this out there, we should make sure it's configured on edge1 as well.  I'm thinking it should be configured on the Controlled Docs / Quality Docs trac for both environments

**Comment by gsteimer** [comment] 2015-08-18 20:00
Main things I want to see for the doc audit trail:

- [ ] Property change audits
- [ ] Obsolete Audit (edge2 only)

**Comment by Swence32** [comment] 2015-08-20 14:05
Updates to ocAduit have been committed and built on edge2. Confirmed that AW workflow audits are not affected by the updates. Need to verify that update properties and effective and obsolete audits appear in the audit trail.

**Comment by gsteimer** [comment] 2015-09-15 18:40
@Swence32 - I went through these steps on edge2 today:

1. Created a Quality Document and routed it for review approval
  - Doing this should change the `aw:status` field for each of our lifecycle aspects.  It should have followed this path: `Draft -> In Review -> Pending Approval -> Approved`
1. After the doc was approved, I updated the effective date attributes
1. Pulled up view audit and I see this:

![image](https://cloud.githubusercontent.com/assets/1377228/9886289/23b1bd30-5baf-11e5-80ed-d6df97099a15.png)

Why does the audit capture the effective date change, but not the `aw:status` property changes?  We definitely need the status changes to show up in the audit trail

**Comment by gsteimer** [comment] 2015-09-15 18:53
Also, after performing a Periodic Review on the document, audit fails with the following error:

```
Caused by: java.lang.NullPointerException
	at com.tsgrp.opencontent.alfresco.audit.AlfrescoEmbAuditImpl.createAddPropsMap(AlfrescoEmbAuditImpl.java:343)
	at com.tsgrp.opencontent.alfresco.audit.AlfrescoEmbAuditImpl.access$300(AlfrescoEmbAuditImpl.java:45)
	at com.tsgrp.opencontent.alfresco.audit.AlfrescoEmbAuditImpl$1$1.handleAuditEntry(AlfrescoEmbAuditImpl.java:231)
```

The code in question is:

```Java
	private Map<String, String> createAddPropsMap(Map<String, String> add){
		Map<String, String> map = new HashMap<String, String>();
		Iterator it = add.entrySet().iterator();
		while (it.hasNext()) {
			Map.Entry pair = (Map.Entry)it.next();
			String addVal = (String) pair.getValue();
			addVal = addVal.substring(addVal.lastIndexOf('}') + 1, addVal.length());
			map.put((String) pair.getKey(), "Property added - " + addVal);
		}

		return map;
	}
```

**Comment by gsteimer** [comment] 2017-06-14 15:54
@Swence32 - can this one be closed?  I just tried power promoting and obsoleting a document on edge2 and it seems to list those events in the view audit action:

![image](https://user-images.githubusercontent.com/1377228/27142144-ce0b134e-50ef-11e7-84ac-a11d3e9e6b06.png)

Not sure if the items discussed above ever got implemented, but it seems that it's at least working from a functional perspective.

**Comment by Swence32** [comment] 2017-06-19 16:30
Yeah we can close this. There may be more client driven enhancements coming to auditing very soon and I can further investigate these and clean up logic at that point.

**Closed** 2017-06-19 16:30 UTC
Labels: Alfresco, Controlled Doc Solution, enhancement
