### ISSUE TITLE
Going back to search from stage with back button sometimes does not re-execute search.

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1082] opened 2016-04-27 18:17 UTC
In certain cases on edge, if you go to the stage from search and then use the back button, it correctly sends you back to the search page and populates the search criteria, but the search results are blank:

![search-back-button](https://cloud.githubusercontent.com/assets/1377228/14863157/3964cac4-0c7a-11e6-87d5-5eabe760fae8.gif)

It looks to me like this is a timing issue.  I've seen this work intermittently with the Wizard trac on edge2, and it seems to work fine on the incident trac.

Also - while looking into this, it may also be a good idea to look to see if #113 is still an issue...

**Comment by joehof** [comment] 2016-06-28 22:11
So this took a little while to track down, but it honestly looks like going back to search with the back button never would have worked when there is a repeating attribute in the form from form support. That code also hasn't been touched since 2013 so this could have always been broken?

The code adds in an empty array value for the repeating, which invalidates the search endpoint request, and no search actually gets run. I'm testing through lots of scenarios now and can confirm soon.

**Comment by gsteimer** [comment] 2016-08-22 20:38
Note - as of 8/15 - this happens all the time since for some reason, we are not putting the full search `GET` URL on the address bar:

![image](https://cloud.githubusercontent.com/assets/1377228/17870788/751ec99c-687e-11e6-8c69-0681f869bf6d.png)

**Comment by renesaladrigas** [comment] 2016-10-27 21:32
ATTRIBUTE SEARCH -- This commit will fix issue seen where search does not re-execute when hitting the back button. This was caused by passing in an empty array (for repeating fields), causing OC to bomb out when re-executing that search on what should have been flagged as an empty parameter. Now, we are checking for an empty array when building up the search parameters to avoid passing in blank parameters.

CR - Joe Hof

Fixed with HPI revision: 16345

**Closed by renesaladrigas** 2016-10-27 21:32 UTC
Labels: issue
