### ISSUE TITLE
Image Viewer Default Priority and Action to Launch it Separately

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1557] opened 2017-12-19 19:03 UTC
Imagine a scenario that you have a document with a JPEG image as the native content and a PDF rendition.

Right now, if you choose to use the "Image Viewer" in your stage config, there is no way to see the annotations of the image without launching OpenAnnotate in a separate tab/window. This is because we have the image viewer priority higher than the OpenAnnotate viewer. The only client to actually use the "Image Viewer/Editor" feature didn't develop an HPI action to be able to launch the "Image Viewer" as an action so there isn't a good way to pull this off right now. 

The quickest enhancement would be:

1) Add a new HPI action for launching the "Image Viewer/Editor" in a new tab (exactly how the OpenAnnotate action works)
2) Change the priority of the "Image Viewe"r to be lower than PDFs

The more permanent/slick solution would be to enhance OpenAnnotate to have image manipulation tools directly within OA when it is viewing an image. We could then just remove the "Image Viewer" component and rely on OpenAnnotate to do the image manipulation.

This is likely dependent on:
https://github.com/tsgrp/OpenAnnotate/issues/162
https://github.com/tsgrp/OpenAnnotate/issues/120

**Comment by gsteimer** [comment] 2017-12-19 19:09
@benallenallen - This is a duplicate of #1541.

**Closed by gsteimer** 2017-12-19 19:09 UTC
Labels: enhancement
