### ISSUE TITLE
AW Question Groups - Table gets shifted on the screen when adding a new row

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#2267] opened 2020-09-14 17:35 UTC
![aw_group_question](https://user-images.githubusercontent.com/8784597/93119014-b91da600-f686-11ea-8dc6-b79787dd1e23.gif)

NOTE: This also seems to happen when removing a row.

**Comment by gsteimer** [comment] 2020-09-14 18:05
Note - this is a duplicate of https://github.com/tsgrp/HPI/issues/1986

**Closed** 2020-09-14 18:09 UTC
Labels: Active Wizard, New Hire, duplicate, issue
