### ISSUE TITLE
HPI Config Archiver and Uploader

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#938] opened 2016-01-04 22:21 UTC
Similar to how the Active Wizard's Page Set Archiver works, it would be nice for HPI to have a way to export and import configs.  Some thoughts:
- Unlike the PSA tool, this should be built as an HPI Admin component rather than a command line tool.
- When uploading configs, if the given config already exists, version it.
- This enhancement is less useful for Alfresco clients (just use ACPs instead), but could be more useful for Documentum clients (Composer can be cumbersome) and HBase clients (no solution in place).

**Comment by dgrumieaux** [comment] 2016-01-04 22:36
Dupe of https://github.com/tsgrp/hpi/issues/613? I think this new issue explains it better

**Comment by gsteimer** [comment] 2016-01-05 16:32
Agreed - I'll close the other issue

**Comment by gsteimer** [comment] 2017-05-30 15:29
Now that we have HPI application IDs, there could also be an option to clone an HPI config to a new App ID.

**Comment by LoganLaFollette** [comment] 2017-08-03 21:10
Fixed:
HPI code at revision: 18452
OC code at revision: 17026

**Closed by LoganLaFollette** 2017-08-03 21:10 UTC
Labels: enhancement, HPI Admin
