### ISSUE TITLE
IE 9: Launching a modal action on the stage obsured by the docviewer

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#630] opened 2015-03-25 19:16 UTC
![selection_008](https://cloud.githubusercontent.com/assets/3905463/6833246/84555078-d2f9-11e4-9571-fb14020833af.png)

**Comment by gsteimer** [comment] 2015-03-25 19:26
@mikeblum  - this is a duplicate of #423

**Comment by gsteimer** [comment] 2015-03-25 19:28
Also - this isn't an IE9 thing, it's an Adobe PDF thing.  I've seen it in Chrome while using Adobe.  I think it's more of a timing thing that the modal displays before the code runs to hide the PDF.

**Comment by gsteimer** [comment] 2015-04-01 16:47
Closing this one as a dupe.  Track this in #423

**Closed by gsteimer** 2015-04-01 16:47 UTC
Labels: duplicate, issue
