### ISSUE TITLE
Workshare Compare - Comparison functionality broken

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1144] opened 2016-07-14 15:23 UTC
See the screencam below - seems like something is wrong with the Workshare Compare integration...

![ws-compare-fail](https://cloud.githubusercontent.com/assets/1377228/16845022/095e184c-49ad-11e6-8365-081d8bef1ab5.gif)

**Comment by ZachGerth** [comment] 2016-07-22 22:12
Investigating this issue, it doesn't look like the code for our HPI Workshare Compare implementation has changed notably since March. I've gone on the server and confirmed the configurations are correct and haven't been updated, and the configurations for edge2 for Workshare Compare are correct according to the documentation as well. 

Possibly, this is related to a deprecated Workshare 5.2 API, but it doesn't look like we really try to contact that beyond getting wsdl schema.

**Comment by ZachGerth** [comment] 2016-07-26 17:01
Note that the commented out way of executing the compare works fine, but the current way doesn't seem to - and neither seems to work in the latest version of OpenAnnotate, which uses the same codebase.

**Comment by ZachGerth** [comment] 2016-07-29 15:41
This was resolved with OC Commit # 14924. The issue was caused by our removal of what seemed to be deprecated package-info code; by restoring this code, rather than forcing the namespace, we restored our helper annotations which took care of these namespaces for us.

**Closed by ZachGerth** 2016-07-29 15:41 UTC
Labels: issue
