### ISSUE TITLE
Reassign Future Approver - Audit should happen at the time of reassignment

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1966] opened 2019-10-08 16:31 UTC
When reassigning a future approver, currently the reassign audit happens at the point where the user gets the task.  Instead, the audit should occur when the actual reassignment happens.

**Comment by gsteimer** [comment] 2019-10-18 20:21
@mwojno-tsg - minor update needed.  I tried this on edge1 and the audit correctly happens at the time of reassignment.  However, the data is slightly wrong.  In the example below, my user `gsteimer` reassigned `qdadmin2` to `qdadmin1`:

![image](https://user-images.githubusercontent.com/1377228/67125612-d9b15780-f1ba-11e9-800b-709f5f331748.png)

However, the audit lists the user that took the action as `qdadmin1` rather than `gsteimer`

**Comment by mwojno-tsg** [comment] 2019-10-21 19:58
The issue is resolved in OC commit 23562. The issue was that I thought the Username was the user who the task was being reassigned or delegated to. While, it should be the username of who did the reassigning or delegating. A simple variable change in both executers resolved this issue.

**Closed by mwojno-tsg** 2019-10-21 19:58 UTC
Labels: Active Wizard, Activiti Workflow, enhancement
