### ISSUE TITLE
Alfresco Image Thumbnails are returned before native content, breaking the stage

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#547] opened 2015-01-22 16:17 UTC
Viewing an excel file in the stage (native content, no PDF) looks like this on Alfresco:

![image](https://cloud.githubusercontent.com/assets/1377228/5859348/4743148c-a21f-11e4-9144-0769e6111e2e.png)

This is because OC is not returning the native content, but the PNG thumbnail instead.  The stage should be making content requests like this:

`pdf,.*`

I'm guessing what's happening is that the Alfresco Impl is not processing the .* syntax properly.  It should return the Excel file and not the thumbnail

Also - it seems like Excel files are being processed through the browser stream viewer.  Is that correct?  I would guess that they should fall to the download viewer.

**Comment by zkeller** [comment] 2015-01-22 16:28
Actually, I think the problem is that it is returning the excel file, but when we query alfresco for the different renditions, it comes back with a png rendition. Since the image viewer is a higher priority than browser stream (or download), it recognizes the image viewer as something that can show a rendition and decides to use that viewer instead of the correct viewer. 

I think the fix would be to fix the Alfresco code to not return the thumbnail renditions as true renditions of the document.

**Comment by joehof** [comment] 2015-02-18 22:12
The getContentFormat method in AlfrescoEmbExtendedContentImpl was returning a node's thumbnail content along with everything else. This was messing up the stage, we shouldn't be returning the thumbnail info unless we absolutely want it.

Fixed with OC revision #10896

**Closed by joehof** 2015-02-18 22:12 UTC
Labels: Alfresco, issue
