### ISSUE TITLE
Search Query Results Coming Back With 999 Results Instead Of 1000

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1893] opened 2019-05-29 16:38 UTC
At some point in the recent past the results coming back from Alfresco was somehow changed from the usual Alfresco limit of 1,000 to 999. See screenshot for reference.

![image](https://user-images.githubusercontent.com/13734523/58574703-2ee9ce00-8206-11e9-800a-1c733b4fb6fa.png)

**Comment by ebrent** [comment] 2019-06-05 16:02
There are several _bad_ documents within the Underwriting/Claims tracs that are causing this issue. It seems the issue is that these documents don't have permissions set to any group, and look something similar to the photo attached. Therefore, the _search_ is returning the full 1000 documents, but will limit the results based on permissions. Alfresco itself is returning 999. Since this is an alfresco issue, the issue will be marked as closed. We will be deleting these specific documents found that are causing this problem.
![image](https://user-images.githubusercontent.com/48491819/58971622-6ebe3180-8781-11e9-830b-6f1e31fe1e3f.png)

**Closed by ebrent** 2019-06-05 16:02 UTC
Labels: Alfresco, Search Results View, issue, tableview, wontfix

**Comment by gsteimer** [comment] 2019-06-05 16:59
Note - once OCMS 3.2 is released, we should test this on QA2.  Edge/release are currently Alfresco 5.1.2, whereas QA is Alfresco 5.2.3.  Perhaps this will simply just work on 5.2.x.
