### ISSUE TITLE
Automated Build Number on Login Screen from SVN

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#204] opened 2014-03-05 17:24 UTC
Login screen would show the SVN revision that was used to compile HPI.

Include with this - compile into an hpi-2.x-<buildnum>.js rather than require.js. That way users don't have to clear js cache when a new HPI webapp is released.

**Comment by gsteimer** [comment] 2017-03-01 18:44
Per @dgrumieaux - When doing this, we'll probably want to use this program: https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-subwcrev.html

**Comment by gsteimer** [comment] 2017-07-19 16:51
@dhartman25 - is this something for Watermelon Hound?

**Comment by cchau-tsgrp** [comment] 2018-05-02 16:58
http://svnbook.red-bean.com/en/1.1/ch08s03.html

**Comment by gsteimer** [comment] 2018-05-03 20:28
Briefly looked at the `subwcrev`.  I think it'd work, but the problem is that it's Windows only and relies on TortoiseSVN being installed.  So, we could integrate this fairly easily into our Jenkins pipeline for edge/release, but I don't think integrating it directly into the build would be a good idea.

**Comment by dgrumieaux** [comment] 2018-05-03 20:31
Svn command line getting the revision is easy too. But not sure we would want to get the rev number this way either.

![screen shot 2018-05-03 at 3 30 18 pm](https://user-images.githubusercontent.com/547941/39601245-f29e47da-4ee6-11e8-89a3-b3272abe6737.png)

**Comment by gsteimer** [comment] 2018-05-03 21:14
@dgrumieaux - yeah, I looked at the `svn` and `svnversion` commands briefly as well.  I don't have those commands, so I'm guessing if we went this route, we'd need to require that anyone installing TortoiseSVN also checks the box during installation to include the command line tools.

**Comment by gsteimer** [comment] 2018-10-05 20:57
Fixed in OCMS 3.1.

**Closed by gsteimer** 2018-10-05 20:57 UTC
Labels: enhancement
