### ISSUE TITLE
Wizard task inbox proxy

### ISSUE THREAD

**Issue by aviking** [tsgrp/hpi#865] opened 2015-10-21 15:50 UTC
This is a 2 part enhancment. Phase 1 will be implementing the solution for Documentum and phase 2 will be impementing this for all ECMs.

Phase 1:
Storing inbox proxy  on user preferences
Updateing the User Preferences config to allow a user to set their inbox proxy
For Dctm, updating the dm_user with the inbox proxy information

Phase 2:
For all other ECM's (which will include Dctm) we will need to implement the getInboxProxyUser method in the ActivitiWorkflowImpl to get the proxy information of the user preferences.
From Phase 1 all the information will already be stored on the userPrefernece object.

Talk to @aking and @gsteimer starting this.

**Comment by gsteimer** [comment] 2015-10-21 17:57
This is a duplicate of #845

**Closed by gsteimer** 2015-10-21 17:57 UTC
Labels: Activiti Workflow, Controlled Doc Solution, duplicate, enhancement
