### ISSUE TITLE
Advanced Combine To PDF - Reordering by changing the index is broken

### ISSUE THREAD

**Issue by keljopap-tsgrp** [tsgrp/HPI#1823] opened 2019-01-25 12:26 UTC
Changing the index no longer does anything in ACTPDF, therefore only allowing the user to reorder rows with the click and drag method.  This could be a problem when using multiple pages.

It used to at least move that row to the index that you entered if it was in the range of the number of docs, or to the last position if it was greater.

![reordering-actpdf-by-index](https://user-images.githubusercontent.com/37815877/51745865-d775fe80-2069-11e9-941d-11d6b77ad80c.gif)

**Comment by Kovacinski** [comment] 2019-01-25 13:57
Was caused by revision 22173

**Comment by gsteimer** [comment] 2019-01-29 17:24
@CRdouglas - @benallenallen says this was fixed on your branch, can you merge back to trunk?

**Comment by CRdouglas** [comment] 2019-04-10 18:51
ORDERINPUTROW ISSUES REORDERING: Reordering with drag and orderinput column now work again after taking out an unnecessary line from a previous commit.

CR - skovacinski/rsaladrigas

At revision: 22731

**Closed by CRdouglas** 2019-04-10 18:51 UTC
Labels: issue, tableview
