### ISSUE TITLE
Non-HPI Admins can get to /admin

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#886] opened 2015-11-04 17:57 UTC
![selection_091](https://cloud.githubusercontent.com/assets/3905463/10946962/cf3a1064-82ea-11e5-8ff7-075f24f07e7a.png)

Admittedly my user isn't a member of ```hpi_administrators``` so my changes throw an odd error:

![selection_092](https://cloud.githubusercontent.com/assets/3905463/10947008/0804490a-82eb-11e5-9165-b8cfe5a62128.png)

```
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating config object: org.alfresco.repo.security.permissions.AccessDeniedException: 10040105 Access Denied.  You do not have the appropriate permis
sions to perform this operation.
        at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:50)
```

shouldn't security.js be routing me to the login page instead? Why is the admin button visible?

**Comment by mikeblum** [comment] 2015-11-04 18:00
It appears to act this way if no groups are configured for application security:

![selection_093](https://cloud.githubusercontent.com/assets/3905463/10947075/83ec79ac-82eb-11e5-8cd7-5951e5c43cd9.png)

Shouldn't the default behavior be to only allow the hpi_administrators group.

**Comment by gsteimer** [comment] 2015-11-04 19:10
@mikeblum - you are correct.  The config in the admin only determines who can see the admin button in the header.  There's nothing stopping someone from going to `/admin`.  However, repository permissions will prevent non-HPI admin users from actually making any changes.

This is something that @joehof's current client noticed - they may be fixing this sometime in the next month or so.

**Comment by gsteimer** [comment] 2015-12-16 18:03
Another item to update along with this:

In the admin, if no groups are configured, the default should be to **deny** all users access to the admin.  I believe the current default is to allow all users, which is not a good idea.

**Comment by mikeblum** [comment] 2015-12-16 18:44
Agreed.  Won't we need to update the router to stop going directly to
/admin in addition to hiding the button.

**Comment by renesaladrigas** [comment] 2015-12-18 22:06
So far the issue is almost completely resolved, pending a few details. Issue was branched to http://svn.tsgrp.com/repos/hpi/feature_branches/admin_router_lockdown.

So far abstractRouter.js does not allow a user to access any of the /admin pages if they are not in one of the groups specified by the app config. If the app config has no allowed groups to admin, it currently allows anyone to access admin. This essentially locks everyone out of the admin, so, correct me if I'm wrong @gsteimer, there should be an additional feature in user preferences that enables or disables a total lockdown of admin in the case no groups are specified in the configs to avoid completely locking out anyone from making admin changes.

**Comment by mikeblum** [comment] 2015-12-23 15:29
Saw that on `hpi_dev_71` it was configured to dm_browse_all - effectively locking out hpi_administrators. The fix was to go to /admin directly and update the config. We'll want to make sure the case of a broken config doesn't lock out administrators.

**Comment by dgrumieaux** [comment] 2015-12-23 17:46
As per group discussion - need to document more scenarios to ensure this issue is addressed correctly:

- User logs in and cannot see existing ApplicationConfig. (Do we even need to support this scenario?)
- User logs in and no ApplicationConfig exists.
- User logs in and ApplicationConfig has no groups authorized for HPI Admin.
- User logs in and is in an authorized group.
- User logs in and is not in an authorized group.

How do we want to support each scenario?

**Comment by dgrumieaux** [comment] 2015-12-23 17:47
as per @mikeblum - may be partially addressed by throwing more informative error messages to the user (not authorized instead of the above error)

**Comment by renesaladrigas** [comment] 2016-09-15 15:42
Here's an update to this issue that pretty much compiles all concerns raised above:

- ApplicationConfig has no groups authorized for HPI Admin and HPI Admin URL is open to everyone

- [ ]  Expected result: Admin button will be visible to anyone, so all can enter Admin without restriction

- ApplicationConfig has groups authorized for HPI Admin and HPI Admin URL is open to everyone

- [ ] Expected result: Admin button will be visible to those in the selected groups, and user who clicks on it will be able to see the Admin immediately. However, anyone can get into the Admin through /admin

- ApplicatinConfig has no groups authorized for HPI Admin and HPI Admin URL is locked down with a username and password (also applies for those entering through /admin)

- [ ] Expected result: Admin button will be visible to anyone, however when clicking the button, the user will have to provide the admin username and password combination to actually log in

- ApplicationConfig has groups authorized for HPI Admin and HPI Admin URL is locked down with a username and password (also applies for those entering through /admin)

- [ ] Expected results: Admin button will be visible to those in the selected groups and when clicking the button, the suer will have to provide the admin username and password combination to actually log in

@gsteimer do these expected behaviors seem reasonable to you? This is the current state of HPI with the latest work done to the admin lockdown for Miami Dade with @joehof

**Comment by gsteimer** [comment] 2016-09-15 20:11
@renesaladrigas - looks good - pending our discussion.  The Admin button should _not_ display if there are no groups configured.

**Comment by renesaladrigas** [comment] 2016-09-20 14:52
ADMIN URL LOCKDOWN - This feature allows for the admin URL to be locked down securely with a username and password, prompting users with an admin login view before entering. If a user is successfully loggged in against the credentials stored in OC, a cookie will be place on its browser that will be used for any further validations against OC to enter the admin. Also included here is the change in behavior of allowed/denied groups in the admin; if no allowed groups exist in the admin, the admin button will not be displayed for anyone.

This issue was closed with revisions:
HPI - 15994
OC -  15193

CR - Joe Hof, George Steimer

**Closed by renesaladrigas** 2016-09-20 14:52 UTC
Labels: HPI Admin, issue, question
