### ISSUE TITLE
Alfresco + GridView: broken on release2 & edge2

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#672] opened 2015-05-11 18:51 UTC
Preforming a search in Grid View on both release2 and edge2 is broken.

![selection_001](https://cloud.githubusercontent.com/assets/3905463/7572541/8c697c84-f7e4-11e4-87bb-301d922273bd.png)

**Comment by cmlewis** [comment] 2015-05-13 17:00
Note this is search controls, the thumbnails and attributes seem fine. Will just need potential markup/CSS updates to fix alignment.

**Comment by cmlewis** [comment] 2015-06-11 02:03
Seems to be only a display issue, although there may be issues when switching between table and grid view. @mikeblum Please add more detail.

**Comment by aviking** [comment] 2015-06-16 16:02
Fixed with HPI Commit: 12460
CR: Zaq

**Comment by cmlewis** [comment] 2015-06-16 16:04
@aviking Was this just a display issue or were there search control bugs as well?

**Comment by aviking** [comment] 2015-06-16 16:08
@cmlewis It was just a display issue caused by the height of the <h4> tag which displays the "title" link.

**Comment by cmlewis** [comment] 2015-06-16 16:15
@aking the display issue I found is caused when multiple document types are configured and one of them has less attributes than the others. Please test out this scenario. It will probably need some CSS wizardry to fix. Thanks!

**Comment by gsteimer** [comment] 2015-06-16 16:17
@aviking - I'm reopening this issue.  Please close it after the scenario mentioned by @cmlewis is verified / fixed.

**Comment by aviking** [comment] 2015-06-16 18:34
You were right @cmlewis the issue was that if you had results with multipul objectTypes coming back and they were configured to show different amounts of properties the clearfix class would hav different heights and that would result in the incorrect display. To fix this I figure out of all the displayed results what the max number of properties will be shown. Based on that we are able to apply the same class to each result that sets the appropiate min-height on that div. I'm attaching a screen shot so you can see the result: 
![goodgridview](https://cloud.githubusercontent.com/assets/2895070/8191196/5ecae920-142c-11e5-8d1e-cfe67e41732c.png)

**Comment by cmlewis** [comment] 2015-06-18 20:57
Thanks Avi. Can you check W3Schools to see what the minimum IE browser version is that supports min-height? I know older versions used to ignore that property.

**Comment by aviking** [comment] 2015-06-19 16:33
I checked and the min-height attribute is compatible with IE7 and up.

Fixed with HPI Commit 12504
CR: Zaq

**Closed by aviking** 2015-06-19 16:33 UTC
Labels: Alfresco, issue, New Hire
