### ISSUE TITLE
Cancel Wizard Workflow does not appear for owner of form on Alfresco

### ISSUE THREAD

**Issue by rosenoam** [tsgrp/HPI#1318] opened 2017-02-27 15:35 UTC
Owner of form on alfresco is unable to cancel the wizard workflow. Attached is the way a user on edge1 vs edge2 sees this now. 
![cancel workflow review on edge2](https://cloud.githubusercontent.com/assets/22036850/23367504/15d8c302-fcd0-11e6-836d-767ed25e67cd.gif)

**Comment by rosenoam** [comment] 2017-02-27 16:00
Condition evaluator is IsUserFormOwnerOrAdministrator

**Comment by gsteimer** [comment] 2017-02-27 17:05
The root cause of this issue is also causing #816

**Comment by gsteimer** [comment] 2017-02-27 19:30
Fixed in OC Rev 16054

**Closed by gsteimer** 2017-02-27 19:30 UTC
Labels: Active Wizard, Activiti Workflow, Alfresco, issue
